<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="NovaPasta\**" />
    <EmbeddedResource Remove="NovaPasta\**" />
    <None Remove="NovaPasta\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentNHibernate" Version="3.4.1" />
    <PackageReference Include="MySql.Data" Version="9.4.0" />
    <ProjectReference Include="..\Dominio\Dominio.csproj" />
  </ItemGroup>

</Project>
